services:
  springboot-app:
    image: dockerspringbootmysql-image1:tag1 # It is your built application image name:tag
    container_name: springbootappcontainer
    ports:
      - "8190:8191"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/dockerexampledb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
    networks:
      - docker-springmysql-network

  mysqldb:
    image: mysql:8.0 # It is image name:version taken from docker hub
    container_name: mysqldbcontainer
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerexampledb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    networks:
      - docker-springmysql-network

networks:
  docker-springmysql-network:
    #driver: bridge